### ISSUE TITLE
blank page and no redirect at page with type 1316773681

### ISSUE THREAD

**Issue by pahy** [kalypsos/social_auth#7]
Hi,

sometimes, the redirect is not working and it ends up in a blank page. It is at the state with type=1316773681.

The complete url is
`https://mydomain/account/?type=1316773681&tx_socialauth_pi1%5Bprovider%5D=google&tx_socialauth_pi1%5Bredirect%5D=https%3A%2F%2Fmydomain%2Faccount%2F`

Sometimes it is working and sometimes not. When this blank page occurs and the page e.g. https://mydomain/account is reloaded without the parameters, the user is logged in.

When a blank page appears, then all following tries with logout and login end up in this.

Typo3 is 8.7.2 with social_auth 1.1.3. Using default formd from social_auth; no felogin integration, no fluid template;

Bye
Patrick

**Comment by in-session** [comment]
Same Problem, EXT not working on 8.7.7.

**Comment by kalypso63** [comment]
Problem is resolved. Please use the latest release (1.1.4). This extension will be on TER shortly

**Comment by in-session** [comment]
Great News :-) but after login we receive an error:
	
Page Not Found
Reason: Request parameters could not be validated (&cHash empty)

?type=1316773681&tx_socialauth_pi1%5Bprovider%5D=facebook&tx_socialauth_pi1%5Bredirect%5D=https%3A%2F%2Fwww.domain.com%2Findex.php%3Fid%3D238#_=_

- no changes with: [FE][cHashExcludedParameters] = tx_socialauth_pi[provider],tx_socialauth_pi[redirect]
- Only with [FE][pageNotFoundOnCHashError] = false is working
- with f:link.page noCacheHash="FALSE" it is also working

After go to an other subpage, the user is logged in.

Cheers Chris

**Comment by kalypso63** [comment]
Problem is resolved now. I added two excludedParameters on ext_localconf.php. Please use last release (1.1.5) and clear all caches

**Comment by in-session** [comment]
After test I get only a blank page and after load a subsite the login also not work

?type=1316773681&tx_socialauth_pi1%5Bprovider%5D=facebook&tx_socialauth_pi1%5Bredirect%5D=https%3A%2F%2Fwww.domain.com%2F

**Comment by kalypso63** [comment]
Please try my current release (1.1.6). Have you clear all caches ?

My current configuration
[FE][pageNotFoundOnCHashError] = true
[FE][cHashExcludedParameters] => is done by extension (tx_socialauth_pi1[provider] & tx_socialauth_pi1[redirect] are excluded by default)

**Comment by in-session** [comment]
Great work, the new version works fine, I've currently tested only with Facebook API.

Works also now with [FE][pageNotFoundOnCHashError] = false

Have a nice day

**Comment by in-session** [comment]
Additional Points:
- LinkedIn get an error ?tx_socialauth_pi1[error]=4
- Google+ works, maybe it is a goode Idear to put the default scope https://www.googleapis.com/auth/userinfo.profile inside

**Comment by kalypso63** [comment]
Hey,

LinkedIn provider error is resolved on next release 1.1.7
https://www.googleapis.com/auth/userinfo.profile is the default profil but you can change it on extension configuration panel

**Comment by in-session** [comment]
Great now it works 👍 

I checked now the database fields.
I think it would be better to not fill the follow fields

LinkedIn:
"fe_user -> country"

Google:
"fe_user -> address" 
"fe_user -> city" 

Because with other extension then there could be a problem with wrong data.

Or what do you think?

**Comment by in-session** [comment]
Sorry again :(

I found a new problem again. I try to explain it to you, my englisch is not the best.

When a user is not loggedin but he makes some ineraktives on the website which set the fe_typo_user cookie then the social login is without function (only the site loads new). After some checks also with felogin it looks like the cookie is unset/renewed after login/logoff. Therefore I believe you need to renew the cookie content after click of the social buttons.

**Comment by kalypso63** [comment]
Hey,
To customize filling of fields, I prefer you use the available signal slot beforeCreateOrUpdateUser on your extension. (Explain in README.md). 

Test with my new release (1.1.8)

**Comment by in-session** [comment]
Hi again :-) 

The problem with the cookie still exists.
And by the way, I see also that the Username is also saved in the database under fe_users.username but this fields needs lowercase datas without spaces etc. I belive it is also better to put here the e-Mailadress inside?

Have a great weekend.

Cheers Chris

**Comment by kalypso63** [comment]
Problem with username mapping is resolved

**Comment by in-session** [comment]
Great many thanks.

About the cookie:
I belive you understand the problem wrong because of my english, sorry.
If this default cookie fe_users set by typo3 in the frontend, no social login it is possible.
Only a reaload of the page but without function of login.
After delete the cookie the social auth login works.

Cheers Christoph

**Comment by kalypso63** [comment]
Hi,

It's a problem with TYPO3 8.7. Could you try with my last commit https://github.com/kalypso63/social_auth/commit/8cef4f0e36f06337e32a01bdd4837c0cfb141fcc ?

**Comment by in-session** [comment]
Hi again,

yes I test it with the current version, but the problem is not resolved.

In additional if the user cancel the login over linkedIn he receives an error after redirect:
Uncaught TYPO3 Exception
#5: Authentication failed! LinkedIn returned an error: user_cancelled_login (More information)
Exception thrown in file
/html/typo3/typo3conf/ext/social_auth/Resources/Private/Librairies/hybridauth/hybridauth/hybridauth/Hybrid/Auth.php in line 169.
 
And the next point is, if the user allready registerd with the same e-mail address the login function don't work because of duplicate user. I believe the best way is to check if the user allready existent before login. Then show an error that he allready have an account wiche is registerred over Provider (tx_socialauth_source).

have a nice evening

Cheers

**Comment by in-session** [comment]
Also after cancelation over facebook:

Could not authorize user, reason: Permissions error (200) 
Exception thrown in file
/html/typo3/typo3conf/ext/social_auth/Resources/Private/Librairies/hybridauth/hybridauth/hybridauth/Hybrid/Auth.php in line 169.

**Comment by kalypso63** [comment]
Hi,

Problem with cancel uri on each provider has been resolved with next release (1.2.0)

The best way to prevent duplicate user is to create a new Storage folder on BO to store only fe_users with social login. Don't forget to set an extension manager the new PID.
I use getUnique from DataHandler to prevent duplicate username on same folder.

For cookie, it's a problem with TYPO3 8.7. If you found the problem please create a PR on my repository.
